version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: embydb
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
    ports:
      - "3306:3306"  # 映射MySQL容器的端口到Windows主机
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
